# Generated by Django 4.0.4 on 2022-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trailer', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('star', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
